# Generated by Django 4.1.7 on 2023-03-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_Instituto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='cpf_cliente',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='cidade_cliente',
            new_name='Cidade',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='endereço_cliente',
            new_name='Endereco',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='estado_cliente',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='nome_cliente',
            new_name='Nome',
        ),
    ]
